"""
Tee Time Watcher (config-driven, GitHub Actions edition)
----------------------------------------------------------
Watches your chosen San Diego municipal golf courses' public tee-sheets for
openings that match your criteria (days/time window/players), and emails
you the instant a match appears — with a direct link so YOU click "book"
yourself.

This script only reads availability data (the same data your browser loads
when you visit the booking page, using your own login). It never submits a
reservation and never touches any payment info.

Settings come from config.json in this same repo (generated by the picker
app) rather than being hardcoded here. Edit config.json any time your
preferences change — no need to touch this file.

Requires your foreUP account email/password (to view the tee sheet) set as
environment variables FOREUP_EMAIL / FOREUP_PASSWORD, and SMTP_EMAIL /
SMTP_APP_PASSWORD for sending the alert email — never hardcode these.
"""

import os
import json
import smtplib
import requests
from email.mime.text import MIMEText
from datetime import datetime, timedelta

LOGIN_URL = "https://foreupsoftware.com/index.php/api/booking/users/login"
API_URL = "https://foreupsoftware.com/index.php/api/booking/times"

FOREUP_EMAIL = os.environ.get("FOREUP_EMAIL")
FOREUP_PASSWORD = os.environ.get("FOREUP_PASSWORD")

# Alert destination — a plain email that arrives as a phone notification too
ALERT_EMAIL = "joelyoon@gmail.com"

SMTP_EMAIL = os.environ.get("SMTP_EMAIL")
SMTP_APP_PASSWORD = os.environ.get("SMTP_APP_PASSWORD")
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

CONFIG_FILE = "config.json"
STATE_FILE = "seen.txt"
DAYS_AHEAD_TO_CHECK = 14

BROWSER_HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36"
    ),
    "Accept": "application/json, text/javascript, */*; q=0.01",
}


def load_config():
    with open(CONFIG_FILE, "r") as f:
        return json.load(f)


def load_seen():
    if not os.path.exists(STATE_FILE):
        return set()
    with open(STATE_FILE, "r") as f:
        return set(line.strip() for line in f if line.strip())


def mark_seen(key):
    with open(STATE_FILE, "a") as f:
        f.write(key + "\n")


def send_alert(message):
    if not SMTP_EMAIL or not SMTP_APP_PASSWORD:
        print("[!] SMTP_EMAIL / SMTP_APP_PASSWORD not set — printing instead of alerting:")
        print(message)
        return False
    msg = MIMEText(message)
    msg["From"] = SMTP_EMAIL
    msg["To"] = ALERT_EMAIL
    msg["Subject"] = "Tee Time Alert"
    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_EMAIL, SMTP_APP_PASSWORD)
            server.sendmail(SMTP_EMAIL, [ALERT_EMAIL], msg.as_string())
        print(f"[✓] Alert sent: {message}")
        return True
    except Exception as e:
        print(f"[!] Failed to send alert: {e}")
        return False


def login(facility_url, course_id):
    """Log in with your foreUP account for a specific course and return a session."""
    session = requests.Session()
    try:
        session.get(facility_url, headers=BROWSER_HEADERS, timeout=15)
    except Exception as e:
        print(f"[!] Could not load booking page before login: {e}")
        return None

    login_headers = dict(BROWSER_HEADERS)
    login_headers.update({
        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        "X-Requested-With": "XMLHttpRequest",
        "X-FU-Golfer-Location": "foreup",
        "Origin": "https://foreupsoftware.com",
        "Referer": facility_url,
    })
    payload = {
        "username": FOREUP_EMAIL,
        "password": FOREUP_PASSWORD,
        "api_key": "",
        "booking_class_id": "",
        "course_id": course_id,
    }
    try:
        resp = session.post(LOGIN_URL, data=payload, headers=login_headers, timeout=15)
        if resp.status_code != 200:
            print(f"[!] Login response status: {resp.status_code}")
            print(f"[!] Login response body: {resp.text[:500]}")
        resp.raise_for_status()
        return session
    except Exception as e:
        print(f"[!] Login failed: {e}")
        return None


def check_date(session, schedule_id, booking_class_id, players, date_str):
    params = {
        "time": "all",
        "date": date_str,
        "holes": "all",
        "players": players,
        "booking_class": booking_class_id,
        "schedule_id": schedule_id,
    }
    try:
        resp = session.get(API_URL, params=params, headers=BROWSER_HEADERS, timeout=15)
        resp.raise_for_status()
        return resp.json()
    except Exception as e:
        print(f"[!] Error checking {date_str}: {e}")
        return []


def in_time_window(time_str, start_str, end_str):
    try:
        t = datetime.strptime(time_str.strip(), "%Y-%m-%d %H:%M").time()
        start = datetime.strptime(start_str, "%H:%M").time()
        end = datetime.strptime(end_str, "%H:%M").time()
        return start <= t <= end
    except Exception:
        return False


def target_dates(target_weekdays, days_ahead=DAYS_AHEAD_TO_CHECK):
    dates = []
    today = datetime.now()
    for i in range(days_ahead):
        d = today + timedelta(days=i)
        if d.weekday() in target_weekdays:
            dates.append(d)
    return dates


def check_course(course_key, course_cfg, cfg, seen):
    name = course_cfg.get("name", course_key)
    if any(v == "REPLACE_ME" or v == "REPLACE_ME_URL" for v in [
        course_cfg.get("schedule_id"), course_cfg.get("booking_class_id"),
        course_cfg.get("course_id"), course_cfg.get("facility_url"),
    ]):
        print(f"[!] {name}: config still has REPLACE_ME values — skipping.")
        return

    session = login(course_cfg["facility_url"], course_cfg["course_id"])
    if session is None:
        print(f"[!] {name}: could not log in — skipping.")
        return

    for d in target_dates(cfg["target_weekdays"]):
        date_str = d.strftime("%m-%d-%Y")
        slots = check_date(
            session, course_cfg["schedule_id"], course_cfg["booking_class_id"],
            cfg["players"], date_str,
        )
        if not isinstance(slots, list):
            continue
        for slot in slots:
            slot_time = slot.get("time", "")
            available = slot.get("available_spots", 0)
            if not slot_time or not in_time_window(slot_time, cfg["time_window_start"], cfg["time_window_end"]):
                continue
            if available and int(available) >= cfg["players"]:
                key = f"{course_key}_{date_str}_{slot_time}"
                if key in seen:
                    continue
                try:
                    friendly_time = datetime.strptime(slot_time.strip(), "%Y-%m-%d %H:%M").strftime("%-I:%M %p")
                except Exception:
                    friendly_time = slot_time
                card_note = " (card required at booking)" if course_cfg.get("requires_card") else ""
                message = (
                    f"{name} opening: {d.strftime('%a %m/%d')} at {friendly_time} "
                    f"({available} spot(s)){card_note}. Book now: {course_cfg['facility_url']}"
                )
                if send_alert(message):
                    mark_seen(key)
                    seen.add(key)


def main():
    if not FOREUP_EMAIL or not FOREUP_PASSWORD:
        print("!! FOREUP_EMAIL / FOREUP_PASSWORD environment variables are not set.")
        return

    cfg = load_config()
    seen = load_seen()

    enabled_courses = {k: v for k, v in cfg.get("courses", {}).items() if v.get("enabled")}
    if not enabled_courses:
        print("!! No courses enabled in config.json.")
        return

    print(f"Checking {len(enabled_courses)} course(s) for days {cfg['target_weekdays']}, "
          f"{cfg['time_window_start']}-{cfg['time_window_end']}, {cfg['players']} player(s).")

    for course_key, course_cfg in enabled_courses.items():
        check_course(course_key, course_cfg, cfg, seen)


if __name__ == "__main__":
    main()
